export enum PROVIDERS {
  // MODAL
  USER_MODEL = "USER_MODEL",
  COUNTER_MODEL = "COUNTER_MODEL",
  DB2_COUNTER_MODEL = "DB2_COUNTER_MODEL",
  // guard
  APP_GUARD = "APP_GUARD",
  // database
  DATABASE_CONNECTION = "DATABASE_CONNECTION",
  DATABASE_CONNECTION_2 = "DATABASE_CONNECTION_2",
}
